# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3      

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.alpine-x64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apsnetapp6:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
        
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: bharathtbr/coverage
          token: ${{ secrets.PAT_TOKEN }} 
          ref: 'test-master'
          
      - name: Replace image in config
        uses: datamonsters/replace-action@v2
        with:
         files: argocd-app-config-main/dev/deployment.yaml
         replacements: '$IMAGE=bharatht08/apsnetapp6:latest'
         
      - run: |
          git add .
          git commit -m "generated"
          git push
         
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: test-master
          base: main
