# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 
        with:
         persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
        
      
        
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: bharathtbr/coverage
          token: ${{ secrets.PAT_TOKEN }} 
          persist-credentials: false
          
      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}     
      
      - name: copy file from template to main dev
        run: |
            cp "argocd-app-config-main/Templates/deployment.yaml" "argocd-app-config-main/dev/deployment.yaml"
            
      - name: Replace image in config
        uses: datamonsters/replace-action@v2
        with:
         files: argocd-app-config-main/dev/deployment.yaml
         replacements: '$IMAGE=bharatht08/apsnetapp6:latest'  
         
      - name: Git commit
        run: |
            git add .
            git commit -m "generated"
            git push origin release/v${{ github.event.inputs.versionName }}
            
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: bharathtbr/coverage
          token: ${{ secrets.PAT_TOKEN }} 
          persist-credentials: false
      
      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/v${{ github.event.inputs.versionName }}
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: bharathtbr
          reviewers: bharathtbr
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
     
          
    
   
